image: maven:3.6.3-jdk-8

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: "$CI_PROJECT_NAME-maven"
  paths:
    - .m2/repository

test:
  stage: test
  script:
    - mvn --version
    - mvn clean test
